- name: Create Job template
  ansible.builtin.template:
    src: m-pipeline.xml
    dest: /tmp/m-pipeline.xml


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-pipeline.xml') }}"
    name: "CI-Pipelines/{{item}}"
    password: admin123
    url: http://44.192.85.252:8080
    user: admin
